<a href="https://colab.research.google.com/github/hmmnyamminji/python/blob/main/Chapter08_%ED%85%8D%EC%8A%A4%ED%8A%B8%EB%B6%84%EC%84%9D(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 텍스트 전처리 - 텍스트 정규화
- NLTK(Natural Language Toolkit)
- punkt: 문장, 단어 토큰화에 사용하는 사전학습 모델
- 약어(Mr., Dr.)와 일반 마침표를 구분해 문장을 올바르게 분리
- punkt_tab : 최신 NLTK에서 punkt 대신 사용하는 토큰화 모델
- stopwords: 영어 불용어(Stop Words) 목록 (약 179개),
            분석에 의미 없는 빈출 단어: the, is, are, you, we 등,
            제거하면 중요 단어에 집중 가능. 피처 수 감소
- wordnet: 영어 어휘 사전 (단어 간 의미 관계 포함),
          Lemmatization(표제어 추출, 어근 추출)시 원형 단어 조회에 사용,
          표제어(Lemma)는 단어의 사전적 기본형 원형 의미
- averaged_perceptron_tagger: 품사 태깅(POS Tagging) 모델.
                              각 단어의 품사(명사/동사/형용사 등)를 자동으로 판별
- omw-1.4: Open Multilingual Wordnet(다국어 Wordnet), wordnet 사용시 함께 필요

In [ ]:
# NLTK 필수 리소스 다운로드, 처음 한 번만 다운로드하면 됨, 다운로드 위치: -/nltk_data/
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

### 문장 토큰화(Sentence Tokenization)

[토큰화(Tokenization)란?]
- 텍스트를 의미 있는 최소 단위(토큰)로 분리하는 전처리 과정
- NLP의 첫 번째 단계: 원시 텍스트 -> 처리 가능한 단위로 변환
- 자연어 처리 (Natural Language Processing)

[sent_tokenize 동작 원리]
- punkt 모델 기반: 마침표(.) 뒤를 무조건 문장 끝으로 보지 않음
- Mr., Dr., etc. 같은 약어와 일반 마침표를 구분해 올바르게 분리
- 마침표·느낌표·물음표를 기준으로 문장 분리

In [ ]:
from nltk import sent_tokenize, word_tokenize
text_sample = ('The Matrix is everywhere its all around us, here even in this   room. '
               'You can see it out your window or on your television. '
               'You feel it when you go to work, or go to church or pay your taxes.')
sentences = sent_tokenize(text = text_sample) # 리스트 안에 문장 분리
print(f'타입: {type(sentences)}, 문장 수: {len(sentences)}')
for s in sentences:
  print('-', s)

sentences

타입: <class 'list'>, 문장 수: 3
- The Matrix is everywhere its all around us, here even in this   room.
- You can see it out your window or on your television.
- You feel it when you go to work, or go to church or pay your taxes.


['The Matrix is everywhere its all around us, here even in this   room.',
 'You can see it out your window or on your television.',
 'You feel it when you go to work, or go to church or pay your taxes.']

### 단어 토큰화(Word Tokenization)

[word_tokenize 동작 원리]
- 공백과 구두점을 기준으로 단어 분리
- 구두점(. , !)도 별도 토큰으로 추출됨, 후처리로 구두점 토큰 제거 필요
- it's -> [it , 's]처럼 축약형도 분리

In [ ]:
sentence = 'The Matrix is everywhere its all around us, here even in this   room. '
words = word_tokenize(sentence)
print(f'딘어 수: {len(words)}')
print(words)  # 리스트안에 단어 분리, 구두점 포함

딘어 수: 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


In [ ]:
import nltk
from nltk import sent_tokenize, word_tokenize

# 문단을 문장별 단어 토큰화 - 문단을 문장 단위로 분리 후 각 문장을 단어 토큰화
def tokenize_text(text):
  sentences = sent_tokenize(text) # 1단계: 문장 분리
  word_tokens = [word_tokenize(s) for s in sentences] # 2단계: 단어 분리
  return word_tokens

word_tokens = tokenize_text(text_sample)
print(f'문장 수: {len(word_tokens)}')
print('첫 번째 문장 단어:', word_tokens[0])

문장 수: 3
첫 번째 문장 단어: ['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


### 불용어(Stop Words) 제거
[불용어(Stop Words)란?]
- 텍스트 분석에서 의미 없는 매우 빈번한 단어들
- 영어 예시: the, a, an, is, are, was, were, in, at, on, he, she ...
- 제거하면 중요한 내용어(Content Word)에 집중 가능
- 피처 수 감소로 모델 학습 속도 향상
- TF-IDF는 빈출 단어 가중치를 자동 낮추지만 명시적 제거도 효과적

[stopwords.words('english')]
- NLTK가 미리 정의한 179개 영어 불용어 목록
- 언어를 바꾸면 다국어 불용어도 사용 가능: 'french', 'german' 등

In [ ]:
# 불용어(Stop Words) 제거
stopwords = nltk.corpus.stopwords.words('english')
print(f'영어 불용어 수: {len(stopwords)}개')
print('예시 (앞 20개):', stopwords[:20])

영어 불용어 수: 198개
예시 (앞 20개): ['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been']


In [ ]:
all_tokens = []
for sentence in word_tokens:
  filtered_words = []
  for word in sentence:
    word = word.lower()
    if word not in stopwords:
      filtered_words.append(word)
  all_tokens.append(filtered_words)

print('\n불용어 제거 후 토큰:')
print(all_tokens) #의미어만 남음



불용어 제거 후 토큰:
[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


### Stemming(어간 추출)

[Stemming이란?]
- 단어의 어미(또는 일부 접미사)를 규칙에 따라 제거해 어간(stem) 추출
- 사전 없이 규칙 기반으로 처리 -> 빠르지만 부정확할 수 있음
- 어미를 잘라 어근 추정, 단어의 끝 부분을 규칙적으로 잘라내는 과정

[Stemming vs Lemmatization 비교]
- Stemming    : 규칙 기반 어미 제거, 빠름, 결과가 실제 단어 아닐 수 있음
- Lemmatization: 사전 기반 원형 반환, 느림, 항상 실제 단어 반환

[Lancaster Stemmer 특징]
- 가장 공격적인 스테머 (어미를 많이 잘라냄)
- Porter Stemmer보다 더 짧은 어근을 생성
- 장점: 속도 빠름, 피처 수 최소화
- 단점: 과도한 축소로 의미 손실 가능 (fancier→fant)

In [ ]:
from nltk.stem import LancasterStemmer

stemmer = LancasterStemmer()
print('[Stemming 결과]')
print('working/works/worked > ', stemmer.stem('working'), stemmer.stem('works'), stemmer.stem('worked'))
#다양한 형태를 하나의 피처로 묶음

print('amusing/amuses/amused >',
      stemmer.stem('amusing'), stemmer.stem('amuses'), stemmer.stem('amused')) #amuse

print('happier/happiest   >', stemmer.stem('happier'), stemmer.stem('happiest'))

print('fancier/faniest   >', stemmer.stem('fancier'), stemmer.stem('fanciest')) #fant 의미를 힗은 부정확한 어근



[Stemming 결과]
working/works/worked >  work work work
amusing/amuses/amused > amus amus amus
happier/happiest   > happy happiest
fancier/faniest   > fant fanciest


### Lemmatization(표제어 추출): 사전적 원형 반환

[Lemmatization이란?]
- WordNet 사전을 참조해 단어의 기본형(Lemma) 반환
- 항상 실제 사전에 있는 단어를 반환 -> 의미 보존

[품사(pos) 하이퍼 파라미터가 필요한 이유]
- 같은 단어도 품사에 따라 원형이 다를 수 있음
- 예: 'better' → 형용사이면 'good', 동사이면 'better'
- 품사를 지정하지 않으면 기본값(명사)으로 처리 -> 부정확 가능

[품사 태그 약어]
- 'v': verb (동사)
- 'a': adjective (형용사)
- 'n': noun (명사)
- 'r': adverb (부사)

In [ ]:
from nltk.stem import WordNetLemmatizer

lemma = WordNetLemmatizer()
print('[Lemmatization 결과 - 품사 명사 필요]')

print('amusing/amuses/amused >', lemma.lemmatize('amusing', 'v'), lemma.lemmatize('amuses', 'v'), lemma.lemmatize('amused', 'v')) #동사 원형 반환

print('happier/happiest(형용사 a) >', lemma.lemmatize('happier', 'a'), lemma.lemmatize('happiest', 'a')) #형용사 원형 반환

print('fancier/fanciest(형용사 a) >',lemma.lemmatize('fancier', 'a'), lemma.lemmatize('fanciest', 'a')) #stemming보다 의미 보존 우수

[Lemmatization 결과 - 품사 명사 필요]
amusing/amuses/amused > amuse amuse amuse
happier/happiest(형용사 a) > happy happy
fancier/fanciest(형용사 a) > fancy fancy


### BOW - 희소 행렬 (COO · CSR)

[BOW(Bag of Words) 행렬의 특성]
- 행: 문서 수 (예: 25,000개)
- 열: 어휘 수 (예: 100,000개)
- 행렬 크기: 25,000 X 100,000 = 25억 개 원소
- 대부분의 문서는 전체 어휘의 극소수만 사용, 99% 이상이 0
- Dense(밀집) 행렬로 저장하면 메모리 낭비 심각

[희소 행렬 저장 방식]
- 0이 아닌 값(비영값)만 저장 -> 메모리·속도 대폭 개선
- COO: 비영값+행위치+열위치 3개 배열 (직관적, 생성 쉬움)
- CSR: 행 단위로 압축 (ML 연산 최적화, 실무 표준)
- CSC: 열 단위로 압축 (열 방향 연산 최적화)

In [ ]:
import numpy as np
from scipy import sparse
#COO(coordinate) 형식
# 비영값. 해당 값의 행 위치, 열 위치를 각각 배열로 저장

#dense 밀집 행렬 > sparse 희소 행렬 변환
dense = np.array([[3,0,1],
                 [0,2,0]])
data    = np.array([3,1,2]) # 비영값
row_pos = np.array([0,0,1]) # 행 위치
col_pos = np.array([0,2,1]) # 열 위치

# coo__matrix 생성: (값배열, (행위치배열. 열위치배열))
sparse_coo = sparse.coo_matrix((data, (row_pos, col_pos))) #희소 행렬 생성

coo_auto = sparse.coo_matrix((data, (row_pos, col_pos))) #자동 변환
print(sparse_coo.toarray()) # danse 밀집 행렬로 변환
print('원본과 동일:', (dense == sparse_coo.toarray()).all())

#dense (밀집) 행렬: 행렬의 모든 원소(0을 포함한 모든 값)를 저장하는 방식, 일반적인 행력
#Sparse (희소) 행렬: 0이 아닌 값(비영값)과 그 위치 정보만을 저장하는 방식, COO와 CSR 형식

[[3 0 1]
 [0 2 0]]
원본과 동일: True


In [ ]:
# CSR (Compressed sparse Row) 형식 - 행(row) 단위로 데이터를 압축 저장
dense2 = np.array([[0,0,1,0,0,5],
                   [1,4,0,3,2,5],
                   [0,6,0,3,0,0],
                   [2,0,0,0,0,0],
                   [0,0,0,7,0,8],
                   [1,0,0,0,0,0]])
data2         = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1]) #행 순서대로 비영값 나열
col_pos2      = np.array([2,5,0,1,3,4,5,1,3,0,3,5,0]) #각 비영값의 열 위치
row_pos_ind   = np.array([0,2,7,9,10,12,13]) #각 행의 해당하는 값이 data2 배열의 위치를 시작 인덱스. 직전 인덱스 (13)
# 0행:data2[0:2], 1행; data2 [2:7], 2행: data2[7:9], 3행: data2[9:10], 4행:data2[10:12], 5행: data2[12:13]
# 마지막 원소: 전체 비영값 수 (13)

# CSR 직접 생성 (값,열위치,행시작인덱스)
sparse__csr = sparse.csr_matrix((data2, col_pos2, row_pos_ind))

print('csr > Dense 변환:')
print(sparse__csr.toarray())

# 더 간편한 방법: Dense 행렬에서 자동 변환
csr_auto = sparse.csr_matrix(dense2)

print('자동 변환 결과 동일:',(csr_auto.toarray() == dense2).all())

csr > Dense 변환:
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
자동 변환 결과 동일: True
